### ISSUE TITLE
How to train a 'M' model?

### ISSUE THREAD

**Issue by Haoxi2002** [Water2sea/WITRAN#2]
Hi, I used your model and ran some 'S' situations very smoothly. But when I set '-- features' to' M ', he will report an error:

> Traceback (most recent call last):
  File "H:\WITRAN\run.py", line 165, in <module>
    main()
  File "H:\WITRAN\run.py", line 129, in main
    _, epoch_time_all_avg = exp.train(setting)
  File "H:\WITRAN\exp\exp_main.py", line 157, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "E:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\WITRAN\models\WITRAN.py", line 163, in forward
    _, enc_hid_row, enc_hid_col = self.encoder_2d(x_input_enc, batch_size, input_size, flag)
  File "E:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\WITRAN\models\WITRAN.py", line 64, in forward
    gate = self.linear(torch.cat([hidden_slice_row, hidden_slice_col, a[:, slice, :]], 
  File "H:\WITRAN\models\WITRAN.py", line 29, in linear
    a = F.linear(input, weight)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (448x389 and 69x192)
 进程已结束,退出代码1

I execute the following command:

```cmd
python run.py --data ETTh1 --data_path ETTh1.csv --features 'M' --seq_len 96 --pred_len 96 --task_id ETTh1_M_96_96 --des ETTh1_M_96_96
```

**Comment by Water2sea** [comment]
Thank you for your interest in our work. When training with multivariables, it is important to first ensure that the parameters 'enc_in', 'dec_in', 'c_out', and the dataset are properly aligned and correspond to each other. Additionally, it is recommended to apply WITRAN separately on different channels, rather than directly modifying the parameters in the code. I hope the above information is helpful to you.

**Comment by Haoxi2002** [comment]
Thank you for your reply. Did you mean to predict each feature separately?

**Comment by Water2sea** [comment]
Considering the independence of channels, it is advisable to process the information extracted from multiple features separately using the WITRAN framework. As for the forecasting module, it is possible to incorporate aggregation operations for multi-channel information.
