### ISSUE TITLE
Request for Scripts

### ISSUE THREAD

**Issue by Nicholas0917** [Water2sea/WITRAN#3]
I have recently come across your paper and accompanying code, and I must express my appreciation for your work. The research and implementation you have shared are truly impressive.

I have been attempting to reproduce the results presented in your paper, but unfortunately, I have encountered difficulties. It seems that I have not been able to achieve comparable outcomes, which I believe could be due to inadequate adjustment of hyperparameters on my part.

In light of this, I am writing to kindly request your assistance. Would it be possible for you to provide me with the scripts or code snippets used in your experiments? Having access to your implementation would greatly aid my understanding and allow me to make the necessary adjustments to reproduce the results accurately.

**Comment by Water2sea** [comment]
Thank you very much for your interest in our work. We did not use the Scripts file you mentioned. For detailed usage information in this regard, you can refer to [[MICN](https://github.com/wanghq21/MICN/blob/main/micn.sh)]. 

The key parameters in WITRAN include d_model, e_layer, WITRAN_deal, and WITRAN_grid_cols. You can adjust them within an appropriate range based on your specific task requirements. Furthermore, when fine-tuning these parameters, you may also consider using other tuning tools such as [[NNI](https://github.com/microsoft/nni)]. 

I hope the above is helpful for you.

**Comment by Nicholas0917** [comment]
Thanks a lot for your prompt response. I will try using the tuning tool you mentioned.
